In [16]:
import numpy as np 
import config
# 修改 my_module.py 文件后
from importlib import reload
reload(config)
config =config.config

In [64]:
with open(config['train_path'],'r',encoding='utf8') as f:
    word_file=[]
    label_file=[]
    for   i  in f.read().strip().split('\n\n'):
        word_line =[]
        label_line = [] 
        for word_label in i.split('\n'):
            word,label=word_label.split(' ')
            word_line.append(word)
            label_line.append(label)
        word_file.append(word_line)
        label_file.append(label_line)
       
   
        
 

In [66]:
word_file[0]
label_file[0]

['O',
 'O',
 'O',
 'B-ORGANIZATION',
 'I-ORGANIZATION',
 'I-ORGANIZATION',
 'I-ORGANIZATION',
 'O',
 'B-TIME',
 'I-TIME',
 'B-LOCATION',
 'I-LOCATION',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O']

In [159]:
import json

In [162]:
with open(r'D:\BaiduNetdiskDownload\nlp学习资料\第九周 序列标注\week9 序列标注问题\ner1\ner_data\schema.json','r',encoding='utf8') as f:
     

In [166]:
len(dic1)

2

In [165]:
dic1 = {"nihao":1,"ss":23}

In [ ]:

data_template = ["2024-07-05 00:00:06","CN2502","E303205616","2203","ASSVI01","WE1",0,11,0 ]

In [107]:
data1 = []

In [150]:
dic1={}
from datetime import datetime, timedelta
start_time = "2024-07-04 01:00:06"
data2=[]
for  i in  range(20):
    new_time = (datetime.strptime(start_time, "%Y-%m-%d %H:%M:%S") +  timedelta(seconds=i*2)).strftime("%Y-%m-%d %H:%M:%S")
    data2.append([new_time,"CN2510","E303205616","2203","ASSVI01","WE1",6+i,11+i,0.8])
    

In [16]:
import torch
import torch.nn as nn

# 假设有3个标签
num_tags = 3

# 创建 CRF 层
crf_layer = nn.CRF(num_tags)

# 模拟模型的 logits 输出
logits = torch.tensor([[-0.5, 0.1, 0.2],
                       [0.3, -0.4, 0.7],
                       [-0.1, 0.4, -0.5]])

# 使用 CRF 层的 decode 方法进行解码
decoded_sequences = crf_layer.decode(logits, torch.tensor([1.0]))

AttributeError: module 'torch.nn' has no attribute 'CRF'

In [13]:
predict

tensor([[ 0.2580, -0.1952, -0.0510],
        [ 0.4043,  0.3063,  0.7373],
        [ 0.0901,  0.0088, -0.2358]], grad_fn=<AddmmBackward0>)

In [31]:
from torchcrf import CRF

num_tags = 5  # 假设有5个标签
crf = CRF(num_tags, batch_first=True)

In [32]:
crf.transitions

Parameter containing:
tensor([[-0.0532, -0.0148,  0.0580, -0.0831, -0.0234],
        [ 0.0337,  0.0686,  0.0816, -0.0789,  0.0310],
        [ 0.0023,  0.0058,  0.0347, -0.0327,  0.0289],
        [ 0.0491, -0.0284,  0.0270, -0.0906,  0.0417],
        [ 0.0411,  0.0153,  0.0583,  0.0956,  0.0894]], requires_grad=True)

In [21]:
logits

tensor([[[ 0.7249,  0.3641, -1.0592],
         [-0.7705, -1.9635, -1.3343],
         [-0.4110, -0.8189, -0.0506]]])

In [117]:
tensor = torch.randn(100000, 10000)

In [118]:
tensor.shape

torch.Size([100000, 10000])

In [119]:
transposed_tensor =tensor.T

In [120]:
transposed_tensor.shape


torch.Size([10000, 100000])

In [121]:
import  time 

In [129]:
start_time = time.time()
contiguous_sum = tensor.mean()
print(tensor.is_contiguous())
print("Time for contiguous tensor:", time.time() - start_time)

True
Time for contiguous tensor: 0.4877164363861084


In [130]:
start_time = time.time()
contiguous_sum1 = transposed_tensor.mean()
print(transposed_tensor.is_contiguous())
print("Time for contiguous tensor:", time.time() - start_time)

False
Time for contiguous tensor: 0.7980363368988037


In [205]:
import   torch

In [207]:
a =  torch.tensor([1017, 1017,   13,  322,  876,  767, 4151,   32, 1966, 1122])


In [208]:
b = torch.stack([a,a])

In [215]:
b.tolist()

[[1017, 1017, 13, 322, 876, 767, 4151, 32, 1966, 1122],
 [1017, 1017, 13, 322, 876, 767, 4151, 32, 1966, 1122]]

In [192]:
for i in torch.stack([a,a]):
    print(i)
    break


tensor([1017, 1017,   13,  322,  876,  767, 4151,   32, 1966, 1122])


In [242]:
import re

text = "这测试是一个测试的例子。"
pattern = "测试"
locations = re.finditer(pattern, text)

for location in locations:
    s, e = location.span()
    print(1)
    print(location.span())
    print(f"匹配位置起始索引：{s}, 结束索引：{e}")
    print(f"匹配的文本：{text[s:e]}")

1
(1, 3)
匹配位置起始索引：1, 结束索引：3
匹配的文本：测试
1
(6, 8)
匹配位置起始索引：6, 结束索引：8
匹配的文本：测试


In [218]:
text[1:3]

'测试'

In [157]:
for  i  in locations:
    s, e = i.span()
    print(s)

In [160]:
type(locations)

callable_iterator

In [171]:
for  i in locations:
    print(i.span())

(1, 3)
(6, 8)


In [177]:
a = [3,2,3,4,5,1]

In [181]:
"".join([str(x) for x in a[:3]])

'323'

In [243]:
a =[1,2,3,4]
b=[2,3,4,5]


In [248]:
[ i if i in b  else  1  for i in a ]

[1, 2, 3, 4]

In [ ]:
[值1 if 条件 else 值2 for 变量 in 可迭代对象]


In [186]:
from collections import defaultdict

In [187]:
schema_dic = defaultdict(list)

In [220]:
config = {
    "sent_len": 20,
    "vocab_path": "./chars.txt",
    "model_path": "",
    "train_path": "./ner_data/train1.txt",
    "test_path": "./ner_data/test.txt",
    "schema_path": "./ner_data/schema.json",
    "schema_size": 9,
    "batch_size": 128,
    "lr": 0.01,
    "epochs": 10,
    "use_crf":True,
    "embedding_dim": 64,
    "optim":'Adam'
}


In [221]:
train_or_test_path = config['test_path']
with open(train_or_test_path, "r", encoding="utf-8") as f:
    word_file = []
    label_file = []
    for i in f.read().strip().split("\n\n"):
        word_line = []
        label_line = []
        for word_label in i.split("\n"):
            word, label = word_label.split(" ")
            word_line.append(word)
            label_line.append(label)
        word_file.append(word_line)
        label_file.append(label_line)
    

[',通过演讲赛、法律知识竞赛,举行法律小品晚会等形式,对官兵进行经常性教育,大力加强了官兵的法纪观念,提高了整个部队的法制建设,杜绝了各类违法乱纪现象的发生。',
 '在邓小平同志逝世一周年的时候,我们缅怀他的丰功伟绩,对他老人家的最好纪念就是响应党的十五大的号召,更高地举起邓小平理论伟大旗帜,兴起一个学习马列主义、毛泽东思想特别是邓小平理论的新高潮,把建设有中国特色社会主义事业全面推向21世纪。',
 '中共中央政治局委员、书记处书记丁关根主持今天的座谈会。',
 '丁关根指出,胡锦涛同志的重要讲话,深刻阐述了高举邓小平理论伟大旗帜、用邓小平理论武装全党的重大意义,深刻阐述了学习邓小平党的建设理论的重大意义,对在新形势下学习和运用邓小平党的建设理论,进一步加强党的建设,提出了明确要求。',
 '我们要认真学习,深刻领会,很好贯彻到学习和工作中去。',
 '今年38岁的邹大明,是全区第一个卖果苗的人。',
 '他自任总经理的成都市名优果品开发公司,拥有几百亩枇杷基地,近几年虽是销售低谷,但年利润也有50万元。',
 '中学刚毕业时,他与女友相中了美满村的一个山坳,如今夫妻俩在这里依托山势盖起了气派的楼房,周围满目葱茏、不见人家,俨然世外桃源。',
 '经常有外地的县长、书记亲自驱车来到山中,请他去传授技术,这些年他走过了一二百个县市。',
 '不过他也有抱怨,慕名前来访问这位“成都市十佳农民”的人太多,每年接待费就有20万元,对一个家庭来说无论如何是太多了。',
 '有分析认为,从目前情形看,贾亚拉莉达还未决定与印度人民党彻底“摊牌”。',
 '据说她曾与国大党方面接触,但国大党暂时还不想和她联手,因为对国大党主席索尼亚·甘地来说,现在出面“倒阁”为时尚早,似乎时机还不成熟。',
 '面对常年出现的长江高潮位和台风暴雨的袭击,张家港市广大干部群众不等、不靠,投资2.3961亿元加固江堤,使之成为高标准长江防洪保安工程。',
 '通过两个冬春的奋战,目前已完成了总投资1.81亿元的工程建设任务,提前完成总工程量的75%,其中完成土石方448万立方米,江堤护堤67公里,治理坍江1.65公里,铺造江堤路面工程59公里,江堤平台和内侧已增种银杏等经济、观赏树木46万株,江堤全线达标,宛若绿色屏障,看上去蔚为壮观。',
 '“老师,日本的墓地为什么建在闹市区呢?”张锋逼问。

In [230]:
''.join(word_file[0])

',通过演讲赛、法律知识竞赛,举行法律小品晚会等形式,对官兵进行经常性教育,大力加强了官兵的法纪观念,提高了整个部队的法制建设,杜绝了各类违法乱纪现象的发生。'

In [231]:
for i in word_file:
    print(i)
    break

[',', '通', '过', '演', '讲', '赛', '、', '法', '律', '知', '识', '竞', '赛', ',', '举', '行', '法', '律', '小', '品', '晚', '会', '等', '形', '式', ',', '对', '官', '兵', '进', '行', '经', '常', '性', '教', '育', ',', '大', '力', '加', '强', '了', '官', '兵', '的', '法', '纪', '观', '念', ',', '提', '高', '了', '整', '个', '部', '队', '的', '法', '制', '建', '设', ',', '杜', '绝', '了', '各', '类', '违', '法', '乱', '纪', '现', '象', '的', '发', '生', '。']


In [238]:
class MyClass:
    def __init__(self):
        self.attribute1 = []
        self.attribute2 = []

    def use_attribute(self, attr_name):
        # 使用 getattr 动态获取属性
        attribute_value = getattr(self, attr_name)
        attribute_value.append(1)
        
        # print(attribute_value)
    def aa(self,attr_name):
        for i in range(11):
            self.use_attribute(attr_name)


# 实例化对象
obj = MyClass()

# 根据传入的属性名动态访问属性
obj.aa('attribute1')  # 输出: This is attribute 1
obj.use_attribute('attribute2')  # 输出: This is attribute 2


In [249]:
stats_dict = {"LOCATION": defaultdict(int),
                           "TIME": defaultdict(int),
                           "PERSON": defaultdict(int),
                           "ORGANIZATION": defaultdict(int)}

In [250]:
stats_dict

{'LOCATION': defaultdict(int, {}),
 'TIME': defaultdict(int, {}),
 'PERSON': defaultdict(int, {}),
 'ORGANIZATION': defaultdict(int, {})}

In [255]:
len([i for  i  in [[],['1']] if i in [[],['2']] and i])

0

In [258]:
len([i for i in  [[],['1','2']] if i ])

1

In [259]:
import  json